/* eslint-disable prettier/prettier */
// This file was generated by a custom prisma generator, do not edit manually.
export const Role = {
  Admin: "Admin",
  Agent: "Agent",
  Banker: "Banker",
  Lowyer: "Lowyer",
} as const;

export type Role = (typeof Role)[keyof typeof Role];
