/* eslint-disable prettier/prettier */
// This file was generated by a custom prisma generator, do not edit manually.
export const Role = {
  USER: "USER",
  ADMIN: "ADMIN",
} as const;

export type Role = (typeof Role)[keyof typeof Role];
